### ISSUE TITLE
'tee' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by pjhammon** [Mabi19/password-game-tas#9]
After installing Node (and Deno,) running the command to start the bot returns an error:

> C:\Your Directory\infinite-craft-bot-main\infinite-craft-bot-main>npm run bot
> infinite-craft-bot@1.0.0 bot
> echo '---BOT START---' >> main.log & node . 2>&1 | tee -a main.log
> 'tee' is not recognized as an internal or external command,
operable program or batch file.

**Comment by pjhammon** [comment]
> After installing Node (and Deno,) running the command to start the bot returns an error:
> 
> > C:\Your Directory\infinite-craft-bot-main\infinite-craft-bot-main>npm run bot
> > infinite-craft-bot@1.0.0 bot
> > echo '---BOT START---' >> main.log & node . 2>&1 | tee -a main.log
> > 'tee' is not recognized as an internal or external command,
> > operable program or batch file.

By installing tee.exe from https://www.geocities.ws/fp.westlake/nt/tee.zip and putting it into the same directory, I no longer get that error, but a different one instead:

Error: Fetch failed with status 403
    at search (C:\Your Directory\infinite-craft-bot-main\infinite-craft-bot-main\main.js:31:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async run (C:\Your Directory\infinite-craft-bot-main\infinite-craft-bot-main\main.js:90:21)

**Comment by Mabi19** [comment]
You're on the wrong repository. This is a Password Game bot.
